database done & map and navbar created
WildCodeSchool-2023-09/JS-RemoteFR-CrewStillant-P3-StreetHunter pull request #43
Opened 2023-12-22 09:21 UTC by Kino-ki

2023-12-22 09:26 UTC, Halicksse approved these changes

2023-12-22 16:36 UTC, Lambseb approved these changes
be careful to commit syntaxe

2023-12-23 09:17 UTC, ioayoub requested changes
Comments + Remove all useless empty files

2023-12-23 09:17 UTC, ioayoub commented on frontend/src/components/ArtworksForm.jsx
> +        title: e.target[0].value,
Something wrong here, you are sending the same value on both lines

2023-12-23 09:17 UTC, ioayoub commented on frontend/src/components/Game/Map/LocateControl.jsx
> +// import * as L from "leaflet";
Remove this file if not used

2023-12-23 09:17 UTC, ioayoub commented on frontend/tailwind.config.js
> +/* eslint-disable prettier/prettier */
Nice try

2023-12-23 09:17 UTC, ioayoub commented on frontend/tailwind.config.js
> +        // eslint-disable-next-line prettier/prettier
Nice try

2023-12-23 09:17 UTC, ioayoub commented on frontend/tailwind.config.js
> +        // eslint-disable-next-line prettier/prettier
👀

2023-12-23 22:18 UTC, Jubdc approved these changes

2023-12-24 00:21 UTC, Jhanemba64 approved these changes

2024-01-03 16:34 UTC, closed without merging